In [36]:
# in this file i am going to learn about the data preprocssing with the use of the python

# Preprocssing in Python

## importing basis packages

In [37]:
# import basic tools
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np 

## importing dataset

In [38]:
# importing data as the dataframe
df=pd.read_csv("Data.csv")

# now our next part is to also find out two different entity :

# a) matrix of feature that is dataset without final column of result  
# b) dependent variable vector (final column)

# easy way using iloc function 

x=df.iloc[:,:-1].values#.values # for matrix of features
y=df.iloc[:,-1:].values#.values # for dependent variable vector

In [39]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [40]:
print(y)

[['No']
 ['Yes']
 ['No']
 ['No']
 ['Yes']
 ['Yes']
 ['No']
 ['Yes']
 ['No']
 ['Yes']]


## Taking care of missing data

In [41]:
# we are going to use simpleImputer from scikit which is one of the great ML library 
from sklearn.impute import SimpleImputer

# the SimpleImputer is a class so lets create a object
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")

# now lets fit the object with the data we want to change 
imputer.fit(x[:,1:])
# this will only change same row 
x[:,1:]=imputer.transform(x[:,1:])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [42]:
# task lets remove missing value from whole database 
m=df.values
# print(m)
imputer.fit(m[:,1:-1])
m[:,1:-1]=imputer.transform(m[:,1:-1])
print(m)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 63777.77777777778 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' 38.77777777777778 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]


## encoding categorical data :<br>
### a) Dependent categorical encoding

In [43]:
# lets do encoding for country as it contains only three countries so for such we have 
# a very good class and encoder present inside the scikit learn (sklearn) they are columntransformer class and
# oneHotEncoder as its encoder

# transformer
from sklearn.compose import ColumnTransformer

#encoder
from sklearn.preprocessing import OneHotEncoder

# now create a object which have functinality according our need 
# [0] is the column which you want to transform
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder="passthrough")

# now transformer is ready to use now we have to use it 
# in ColumnTransformer you have a function fitTransformer so you dont have to do differently 
# which you have to do in removing missing values 
x=np.array(ct.fit_transform(x))

In [44]:
# also change main database 
m=ct.fit_transform(m)
print(m)

[[1.0 0.0 0.0 44.0 72000.0 'No']
 [0.0 0.0 1.0 27.0 48000.0 'Yes']
 [0.0 1.0 0.0 30.0 54000.0 'No']
 [0.0 0.0 1.0 38.0 61000.0 'No']
 [0.0 1.0 0.0 40.0 63777.77777777778 'Yes']
 [1.0 0.0 0.0 35.0 58000.0 'Yes']
 [0.0 0.0 1.0 38.77777777777778 52000.0 'No']
 [1.0 0.0 0.0 48.0 79000.0 'Yes']
 [0.0 1.0 0.0 50.0 83000.0 'No']
 [1.0 0.0 0.0 37.0 67000.0 'Yes']]


### b) Independent Categorical Encoding

In [45]:
# # simple variable encoding
# n=[]
# for i in y:
#     # print(i)
#     if i=="No":
#         n.append(0)
#     else:
#         n.append(1)

# y=n

In [46]:
# so for this we are going to use the labelencoder from the scikitpreprocessing
from sklearn.preprocessing import LabelEncoder

# create a object for the class
le=LabelEncoder()

# just send dvv to encoder and your work is done 
y=le.fit_transform(y)

# for such cases we have x and y so that we can apply different ColumnTransformer 
# without distracting each other 

/home/ghansham/.local/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [47]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting data in Test and Training set

In [62]:
# we get 4 set after spliting data and they are 2 from matrix of feature and 2 from dependent variable vector 

# we are going to use test_train_split function from the sklearn library
from sklearn.model_selection import train_test_split

# so now straightly use the function to get test and train sets 
xTrain,xTest,yTrain,yTest=train_test_split(x,y)

# lets study what argument train_test_split takes
# x : matrix of feature
# y : dependent variable vector
# test_size : aa and aa is fraction from 1 and if you multipy it with 100 you will get % of test data and remaining will train set 
# random_state=1 means select entries randomly and it will put entries randomly in test and train set 

In [63]:
print(xTrain)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]]


In [64]:
print(yTrain)

[0 0 1 0 0 0 1]


In [65]:
print(xTest)

[[0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [57]:
print(yTest)

[1 0]


## Feature scaling

In [68]:
# now lets get standardscalar to apply feature scaling 
# we only apply feature scaling on x train 

# import standardscalar and it is a class
from sklearn.preprocessing import StandardScaler
ss=StandardScaler() # dont have to pass any argument

xTrain[:,3:]=ss.fit_transform(xTrain[:,3:])

In [69]:
print(xTrain)

[[0.0 0.0 1.0 -0.15791351973305862 -1.2832001394292931]
 [0.0 1.0 0.0 -1.6899517024064163 -1.0808431712589666]
 [1.0 0.0 0.0 -0.46819973394538433 0.23447712184815628]
 [1.0 0.0 0.0 0.7535522345156476 0.7403695422739728]
 [0.0 0.0 1.0 -0.2936637384509512 -0.3725937826628235]
 [0.0 1.0 0.0 1.8007682074822464 1.853332867210769]
 [0.0 1.0 0.0 0.055408252537915086 -0.09154243798181402]]


In [70]:
# now apply feature scaling on xtest and we dont have to use fit with xtest as it can lead to info leak
# just use transform from same scalar

xTest[:,3:]=ss.transform(xTest[:,3:])

In [71]:
print(xTest)

[[0.0 0.0 1.0 -2.2135596888897155 -1.6879140757699465]
 [1.0 0.0 0.0 1.4516962164933802 1.4486189308701158]
 [1.0 0.0 0.0 -0.8172717249342506 -0.6761292349183133]]
