# Heart Disease Prediction System

## Importing libraries

In [21]:
import pandas as pd
import  matplotlib.pyplot as plt
import numpy as np

## Importing dataset

In [22]:
data=pd.read_csv("heart.csv")

# now creating matrix of feature and dependent variable vector 
print(data)
x=data.iloc[:,1:-1].values
y=data.iloc[:,-1:].values


         id  gender   smoking_status  hypertension ever_married  \
0      9046    Male  formerly smoked             0          Yes   
1     51676  Female     never smoked             0          Yes   
2     31112    Male     never smoked             0          Yes   
3     60182  Female           smokes             0          Yes   
4      1665  Female     never smoked             1          Yes   
...     ...     ...              ...           ...          ...   
5105  18234  Female     never smoked             1          Yes   
5106  44873  Female     never smoked             0          Yes   
5107  19723  Female     never smoked             0          Yes   
5108  37544    Male  formerly smoked             0          Yes   
5109  44679  Female          Unknown             0          Yes   

     Residence_type  avg_glucose_level   bmi   age  stroke  heart_disease  
0             Urban             228.69  36.6  67.0       1              1  
1             Rural             202.21   Na

In [23]:
pd.DataFrame(x)

0                1  2    3      4       5     6     7  8
0       Male  formerly smoked  0  Yes  Urban  228.69  36.6  67.0  1
1     Female     never smoked  0  Yes  Rural  202.21   NaN  61.0  1
2       Male     never smoked  0  Yes  Rural  105.92  32.5  80.0  1
3     Female           smokes  0  Yes  Urban  171.23  34.4  49.0  1
4     Female     never smoked  1  Yes  Rural  174.12  24.0  79.0  1
...      ...              ... ..  ...    ...     ...   ...   ... ..
5105  Female     never smoked  1  Yes  Urban   83.75   NaN  80.0  0
5106  Female     never smoked  0  Yes  Urban   125.2  40.0  81.0  0
5107  Female     never smoked  0  Yes  Rural   82.99  30.6  35.0  0
5108    Male  formerly smoked  0  Yes  Rural  166.29  25.6  51.0  0
5109  Female          Unknown  0  Yes  Urban   85.28  26.2  44.0  0

[5110 rows x 9 columns]

## taking care of missing data

In [24]:
from sklearn.impute import SimpleImputer

# create object for the simpleImputer
si=SimpleImputer(missing_values=np.nan,strategy="mean")
si.fit(x[:,5:7])
x[:,5:7]=si.transform(x[:,5:7])

In [25]:
# checking that is there a null value remained or not 
pd.DataFrame(x).isnull()

0      1      2      3      4      5      6      7      8
0     False  False  False  False  False  False  False  False  False
1     False  False  False  False  False  False  False  False  False
2     False  False  False  False  False  False  False  False  False
3     False  False  False  False  False  False  False  False  False
4     False  False  False  False  False  False  False  False  False
...     ...    ...    ...    ...    ...    ...    ...    ...    ...
5105  False  False  False  False  False  False  False  False  False
5106  False  False  False  False  False  False  False  False  False
5107  False  False  False  False  False  False  False  False  False
5108  False  False  False  False  False  False  False  False  False
5109  False  False  False  False  False  False  False  False  False

[5110 rows x 9 columns]

# Encode categorical data

In [26]:
# the dependent vector is already encoded so we dont have to do it so now we want to enode remaining once 

# labelencoder for 4,7,8
# onehotencoder for 8

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# create object for the ColumnTransformer
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
x=ct.fit_transform(x)


In [27]:
print(pd.DataFrame(x))

       0    1    2    3       4  5    6      7       8          9     10 11
0     0.0  1.0  0.0  0.0    Male  0  Yes  Urban  228.69       36.6  67.0  1
1     0.0  0.0  1.0  0.0  Female  0  Yes  Rural  202.21  28.893237  61.0  1
2     0.0  0.0  1.0  0.0    Male  0  Yes  Rural  105.92       32.5  80.0  1
3     0.0  0.0  0.0  1.0  Female  0  Yes  Urban  171.23       34.4  49.0  1
4     0.0  0.0  1.0  0.0  Female  1  Yes  Rural  174.12       24.0  79.0  1
...   ...  ...  ...  ...     ... ..  ...    ...     ...        ...   ... ..
5105  0.0  0.0  1.0  0.0  Female  1  Yes  Urban   83.75  28.893237  80.0  0
5106  0.0  0.0  1.0  0.0  Female  0  Yes  Urban   125.2       40.0  81.0  0
5107  0.0  0.0  1.0  0.0  Female  0  Yes  Rural   82.99       30.6  35.0  0
5108  0.0  1.0  0.0  0.0    Male  0  Yes  Rural  166.29       25.6  51.0  0
5109  1.0  0.0  0.0  0.0  Female  0  Yes  Urban   85.28       26.2  44.0  0

[5110 rows x 12 columns]


In [28]:
# now lets do label encoding 

from sklearn.preprocessing import LabelEncoder

# create object for the label encoder 
le=LabelEncoder()
x[:,4]=le.fit_transform(x[:,4])
x[:,6]=le.fit_transform(x[:,6])
x[:,7]=le.fit_transform(x[:,7])

# and now we are done with the encoding 

In [29]:
# encoded matrix of feature
print(pd.DataFrame(x))

       0    1    2    3  4  5  6  7       8          9     10 11
0     0.0  1.0  0.0  0.0  1  0  1  1  228.69       36.6  67.0  1
1     0.0  0.0  1.0  0.0  0  0  1  0  202.21  28.893237  61.0  1
2     0.0  0.0  1.0  0.0  1  0  1  0  105.92       32.5  80.0  1
3     0.0  0.0  0.0  1.0  0  0  1  1  171.23       34.4  49.0  1
4     0.0  0.0  1.0  0.0  0  1  1  0  174.12       24.0  79.0  1
...   ...  ...  ...  ... .. .. .. ..     ...        ...   ... ..
5105  0.0  0.0  1.0  0.0  0  1  1  1   83.75  28.893237  80.0  0
5106  0.0  0.0  1.0  0.0  0  0  1  1   125.2       40.0  81.0  0
5107  0.0  0.0  1.0  0.0  0  0  1  0   82.99       30.6  35.0  0
5108  0.0  1.0  0.0  0.0  1  0  1  0  166.29       25.6  51.0  0
5109  1.0  0.0  0.0  0.0  0  0  1  1   85.28       26.2  44.0  0

[5110 rows x 12 columns]


In [30]:
print(pd.DataFrame(y))

      0
0     1
1     0
2     1
3     0
4     0
...  ..
5105  0
5106  0
5107  0
5108  0
5109  0

[5110 rows x 1 columns]


## spliting dataset

In [31]:
# now we are going to split data in 4 parts and at this stage our preprocessing process ends 

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=1)

In [32]:
print(len(xtrain))
print(len(xtest))
print(len(ytrain))
print(ytrain)

# and spliting completed

3832
1278
3832
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


## feature scaling using standardscaler

In [33]:
# in logistic regression of feature scaling not worth anything
# We need to perform Feature Scaling when we are dealing with Gradient Descent Based algorithms 
# (Linear and Logistic Regression, Neural Network) and Distance-based algorithms (KNN, K-means, SVM) 
# as these are very sensitive to the range of the data points
pd.DataFrame(x)


0    1    2    3  4  5  6  7       8          9     10 11
0     0.0  1.0  0.0  0.0  1  0  1  1  228.69       36.6  67.0  1
1     0.0  0.0  1.0  0.0  0  0  1  0  202.21  28.893237  61.0  1
2     0.0  0.0  1.0  0.0  1  0  1  0  105.92       32.5  80.0  1
3     0.0  0.0  0.0  1.0  0  0  1  1  171.23       34.4  49.0  1
4     0.0  0.0  1.0  0.0  0  1  1  0  174.12       24.0  79.0  1
...   ...  ...  ...  ... .. .. .. ..     ...        ...   ... ..
5105  0.0  0.0  1.0  0.0  0  1  1  1   83.75  28.893237  80.0  0
5106  0.0  0.0  1.0  0.0  0  0  1  1   125.2       40.0  81.0  0
5107  0.0  0.0  1.0  0.0  0  0  1  0   82.99       30.6  35.0  0
5108  0.0  1.0  0.0  0.0  1  0  1  0  166.29       25.6  51.0  0
5109  1.0  0.0  0.0  0.0  0  0  1  1   85.28       26.2  44.0  0

[5110 rows x 12 columns]

## start building a simple regreesion model on top of th training dataset

In [34]:
from sklearn.linear_model import LogisticRegression 

model=LogisticRegression()

# now train the model 
model.fit(xtrain,ytrain)

/home/ghansham/.local/lib/python3.10/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/ghansham/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [42]:
# get predicted values
yPredicted=model.predict(xtest)
yPredicted

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
# sidewise view
m=pd.DataFrame()

# np.set_printoptions(precision=2)
m.insert(column="original",value=yPredicted,loc=0)
m.insert(column="predicted",value=yPredicted,loc=1)

# exporting result
m.to_csv("originalXpredicted.csv",index=0)

In [ ]:
model.predict(np.array([[0.0 ,1.0 ,0.0 ,0.0 ,1,0,1,1,5.2552469620248146,0.20114620356434534,1.6260574023809466,1]]))

array([0])

In [ ]:
pd.DataFrame(xtest[31])

0
0     1.0
1     0.0
2     0.0
3     0.0
4       0
5       0
6       1
7       0
8   57.92
9    22.3
10   33.0
11      0

In [ ]:
print(yPredicted)

[0 0 0 ... 0 0 0]


In [ ]:
from sklearn.metrics import accuracy_score,precision_score,r2_score
print("accuracy using logistic regression : ",accuracy_score(ytest,yPredicted))

print("precision : ",precision_score(ytest,yPredicted))
print("r2 Score : ",r2_score(ytest,yPredicted))

accuracy using logistic regression :  0.9475743348982786
precision :  0.5
r2 Score :  -0.05532617671345985


# predicting 