# Polynomial Linear Regression Model

### importing Libraries

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 

### importing dataset and creating MOF and DVV

In [11]:
data=pd.read_csv("Position_Salaries.csv")

# creating matrix of feature and dependent variable vector
x=data.iloc[:,1:-1]
y=data.iloc[:,-1]

In [12]:
print(pd.DataFrame(x),"\n\n",pd.DataFrame(y))

   Level
0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10 

     Salary
0    45000
1    50000
2    60000
3    80000
4   110000
5   150000
6   200000
7   300000
8   500000
9  1000000


### Buidling linear regression model

here we are going to split as this dataset is different kind of dataset

In [13]:
from sklearn.linear_model import LinearRegression

# now build the model 
lr=LinearRegression()
lr.fit(x,y)

LinearRegression()

In [19]:
# now our model is build model you can say that is dataset is linear or not 
# from the performance of the 
lr.predict([[1]])

/home/ghansham/.local/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-114454.54545455])

### Build a polynomial model

In [39]:
# first convert normal matrix of feature to polynomial matrix of feature (polynomialFeture class is used) and just
#  train it like multiple linear regression model 

from sklearn.preprocessing import PolynomialFeatures

# check result by changing degree
polyRegression=PolynomialFeatures(degree=2)
x_poly=polyRegression.fit_transform(x)

In [40]:
print(x_poly)

[[  1.   1.   1.]
 [  1.   2.   4.]
 [  1.   3.   9.]
 [  1.   4.  16.]
 [  1.   5.  25.]
 [  1.   6.  36.]
 [  1.   7.  49.]
 [  1.   8.  64.]
 [  1.   9.  81.]
 [  1.  10. 100.]]


In [41]:
# build Polynomial linear Regression model like a MLRM 

from sklearn.linear_model import LinearRegression
plr=LinearRegression()
plr.fit(x_poly,y)

LinearRegression()

In [42]:
plr.predict([[1,1,1]])

array([118727.27272727])

## visulizing models